spring:
  application:
    name: JWBigData
  datasource:
    dynamic:
      primary: jw #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        jw:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/jw
          username: root
          password: 123456
        uploaddb:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/uploaddb
          username: root
          password: 123456
        cleandb:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/cleandb
          username: root
          password: 123456
        sparadb:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/sparadb
          username: root
          password: 123456
        modelresultdb:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/modelresultdb
          username: root
          password: 123456
    data:
      redis:
        host: 127.0.0.1
        port: 6379
        #      password: 123456
        database: 0
        lettuce:
          pool:
            max-active: 8
            max-wait: 1
            max-idle: 8
            min-idle: 0
        timeout: 0

  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: false
    global-config:
      enable-sql-runner: true
      db-config:
        logic-delete-field: isDelete
        logic-delete-value: 1
        logic-not-delete-value: 0
table:
  human:
    humanTable: baset
    humanId: PersonId
    humanName: name
  company:
    companyTable: std_mzj_shzzb
    companyId: tyshxydm
    companyName: shzzmc

